[template]
cargo_generate_version = ">=0.7.0"

[placeholders.username]
type = "string"
prompt = "GitHub username (or organization)?"

[placeholders.project-description]
type = "string"
prompt = "Project description?"
